spring.application.name=encantometrobackend
server.port=3000
spring.datasource.url=${DB_HOST}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.profiles.active=${ACTIVE_PROFILE:dev}